version: '3'
services:
  node:
    image: node:17-alpine3.12
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html:cached
    ports:
      - 3000:3000
    environment:
      - BEARER_TOKEN=<your_bearer_token>
  python:
    image: intimatemerger/mecab-ipadic-neologd
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html:cached
      - ./app/pip_modules:/pip_modules
    environment:
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - PYTHONUSERBASE=/pip_modules

