name: Daily Update

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 17
  
    - name: update data
      env:
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      run: |
        cd app
        npm install
        node ./src/script/retrieveTweetsCount.js
        node ./src/script/retrieveSearchRecent.js
        node ./src/script/determinePopular.js
  python-container:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: intimatemerger/mecab-ipadic-neologd
    steps:
    - uses: actions/checkout@v2
    - name: python exec
      env:
        PYTHONIOENCODING: utf-8
        LANG: C.UTF-8
        PYTHONUSERBASE: ./pip_modules
      run: |
        cd app
        pip install pymlask --user
        python ./src/script/analyzeSentiment.py
    # - name: Simple commit
    #   uses: zwaldowski/git-commit-action@v1
    
    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     branch: ${{ github.ref }}

