name: Daily Update

on:
  workflow_dispatch:
jobs:
  node-update:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 17
  
    - name: update data
      env:
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      run: |
        cd app
        npm install
        node ./src/script/retrieveTweetsCount.js
        node ./src/script/retrieveSearchRecent.js
        node ./src/script/determinePopular.js
        node ./src/script/summarizeAnnotation.js
    
    - name: upload data to artifact
      uses: actions/upload-artifact@v2
      with:
        name: output-json-data
        path: ./app/src/data

  python-update:
    needs: node-update
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    container:
      image: intimatemerger/mecab-ipadic-neologd
    steps:

    - uses: actions/checkout@v2

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2
      with:
        name: output-json-data
        path: ./app/src/data

    - name: python exec
      working-directory: ./app
      env:
        PYTHONIOENCODING: utf-8
        LANG: C.UTF-8
        PYTHONUSERBASE: ./pip_modules
      run: |
        pip install pymlask
        python ./src/script/analyzeSentiment.py
    
    - name: upload data to artifact
      uses: actions/upload-artifact@v2
      with:
        name: output-json-data
        path: ./app/src/data

  node-build:
    needs: python-update
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 17

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2
      with:
        name: output-json-data
        path: ./app/src/data       

    - name: Build site
      run: |
        cd app
        npm install
        npm run build

    - name: Deploy to pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./app/build

