name: Daily Update

on:
  schedule:
    - cron:  '45 14 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 17
  
    - name: update data
      run: |
        cd app
        npm install
        node ./src/retrieveData.js

    - name: Simple commit
      uses: zwaldowski/git-commit-action@v1
    
    - name: action-push
      uses: ludeeus/action-push@0.0.1
