name: Daily Update

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 17
  
    - name: update data
      env:
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      run: |
        cd app
        npm install
        node ./src/script/retrieveTweetsCount.js
        node ./src/script/retrieveSearchRecent.js
        node ./src/script/determinePopular.js
    
    - name: upload data to artifact
      uses: actions/upload-artifact@v2
        with:
          name: output-json-data
          path: ./app/src/data

  python-container:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: intimatemerger/mecab-ipadic-neologd
    steps:

    - uses: actions/checkout@v2

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2

    - name: python exec
      working-directory: ./app
      env:
        PYTHONIOENCODING: utf-8
        LANG: C.UTF-8
        PYTHONUSERBASE: ./pip_modules
      run: |
        pip install pymlask --user
        python ./src/script/analyzeSentiment.py
    # - name: Simple commit
    #   uses: zwaldowski/git-commit-action@v1
    
    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     branch: ${{ github.ref }}

